### ISSUE TITLE
new DDF2

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmigaTS#1]
can I already start to download the adfs in the subdirs of vAmigaTS/Agnus/DDF2/ and begin the test on A1000Agnus8367R0 ? Or should I wait ?

**Comment by dirkwhoffmann** [comment]
> Or should I wait ?

Yes, please wait. I rushed a bit with the upload and want to rework the tests first.

**Comment by mithrendal** [comment]
Take your time. There is no hurry. 🙃

**Comment by dirkwhoffmann** [comment]
ddfstrt1 to ddfstrt9 and ddf1strt1h to ddfstrt9h are go 🚀.

**Comment by dirkwhoffmann** [comment]
I've recomputed all images on the MMSE (Rev. 8A A500). 

They all match the rev. 6A pics. Hence, for the yet existing tests, Agnus revisions 8375 and 8372A match.

**Comment by mithrendal** [comment]
I am just transferring disks... soo slow. We will know soon how number 8367R0 does the job...

BTW: How can I pack all those tests on one disk, maybe not so easy possible, no ? I will have to look into it .... maybe I can put all test in one disk and iterate with keyboard ?  Unfortunately it does not boot into CLI, since then I would be able to copy all the tests into one disk and execute them one by one. It is another format, Amiga Workbench shows DF0:NDOS ...

**Comment by mithrendal** [comment]
![FEB106BF-E174-430A-A6EF-197BF4C9E6AD](https://user-images.githubusercontent.com/17108995/65821990-4fba4280-e23d-11e9-9e5c-e9286f835247.jpeg)


Oh it is so beautiful.... it flickers like hell... is yours flickering too?  Maybe I should upload an Apple Live-Photo which shows 3sec Video?

8367R0 draws ddfstrt1 so different compared to 8375 and 8372A

**Comment by mithrendal** [comment]
![A542C2DD-2DBE-4F5B-AD58-11AE622921D2](https://user-images.githubusercontent.com/17108995/65822193-18996080-e240-11e9-9349-971656a728d9.jpeg)
8367R0 drawing ddfstrt1H

**Comment by mithrendal** [comment]
![ADE253DA-8A73-40BD-AFCE-C1069C5115EF](https://user-images.githubusercontent.com/17108995/65822448-6d3eda80-e244-11e9-9501-d080b5aee373.jpeg)


8367R0 drawing ddfstrt2

**Comment by dirkwhoffmann** [comment]
> Oh it is so beautiful.... it flickers like hell... is yours flickering too? 

No, it doesn't flicker on the A500, but it flickers in UAE. I think if A500 OCS is selected in UAE, it tries to emulate the old Agnus. 

Two days ago, I was in good hope to solve the DDF puzzle, but with the latest tests (ddfstrt10 to ddfstrt12) I am left in confusion. In these tests, I boldly swapped the values of DDFSTRT and DDFSTOP (meaning that DDFSTRT is now bigger than DDFSTOP). If I interpret the A500 images for those tests correctly, DMA is switched off *before* the horizontal position counter matches DDFSTOP. This proves my original hypothesis about the DDF logic wrong (which was based on the assumption that Agnus compares the horizontal position counter with DDFSTRT and DDFSTOP). 

My new theory is that Agnus loads a counter when the horizontal position matches DDFSTRT and compares the counter value  (and not the current horizontal position) with DDFSTOP. The counter might be loaded with DDFSTRT at the start of the first fetch unit and is therefore not always aligned to the horizontal position counter. But that's just another theory... and most of the time, new theories are wrong...

**Comment by dirkwhoffmann** [comment]
> We will know soon how number 8367R0 does the job...

I've just uploaded the A1000 reference images to the repo 😎.

> BTW: How can I pack all those tests on one disk, maybe not so easy possible, no ? 

I think it's not possible (or at least very difficult), because of the disk format the Alpine9000 framework is using. I have no real clue how the framework stores the data on disk. I guess they are kind of hard-coded and the boot loader grabs the data directly from some certain tracks.

**Comment by dirkwhoffmann** [comment]
Here is a list of tests vAmiga is supposed to pass. For those tests, it would be interesting to see how they look like on an A1000:

- ddfstr1 to ddfstrt9
- ddfstrt1h to ddfstrt9h
- ddfskip1, ddfskip2

The following tests *won't* be passed by vAmiga in the near future. They can be neglected for the time being:

- dffstrt10 to ddfstrt15
- dffstrt10h to ddfstrt15h
- ddfinv1 to ddfinv5

From the old DDF test suite, ddf7 is important.

**Comment by mithrendal** [comment]
![D1B3C7C4-60ED-4D86-A410-62BBAD8539AF](https://user-images.githubusercontent.com/17108995/65879604-750b9580-e390-11e9-9abb-33937a201199.jpeg)

Ddfstrt3 A1000

**Comment by mithrendal** [comment]
![619E4180-96A1-4025-98CE-A1DB7C3C56EB](https://user-images.githubusercontent.com/17108995/65907479-bcac1480-e3c4-11e9-9921-09a00bfdd42b.jpeg)
ddfstrt4 A1000

**Comment by mithrendal** [comment]
![A1C96C55-85FA-4129-8928-9E9072E9FF03](https://user-images.githubusercontent.com/17108995/65908378-9be4be80-e3c6-11e9-9199-5b001152ed79.jpeg)
ddfstrt5 A1000

**Comment by mithrendal** [comment]
![A095FEDB-0F77-419E-A689-BA6E8325E88C](https://user-images.githubusercontent.com/17108995/65908499-d9494c00-e3c6-11e9-8d90-959e9730332b.jpeg)

Ddfstrt6 A1000

**Comment by mithrendal** [comment]
![F0DC06EC-CB4C-4D74-BAF0-80AB6E077651](https://user-images.githubusercontent.com/17108995/65909165-49a49d00-e3c8-11e9-9e20-8c6b106d37c3.jpeg)
Ddfstrt7 a1000

**Comment by mithrendal** [comment]
![C4FEC100-775F-4E66-8C11-25A743F3AE3A](https://user-images.githubusercontent.com/17108995/65909278-8c667500-e3c8-11e9-8da9-2f7be6794bc4.jpeg)

Ddfstrt8 a1000

**Comment by mithrendal** [comment]
![20F3C90B-0831-4253-A4E6-ADCBD14886EE](https://user-images.githubusercontent.com/17108995/65909419-e7986780-e3c8-11e9-823c-dc2f43de5371.jpeg)
Ddfstrt9 a1000

**Comment by mithrendal** [comment]
Ddfskip1 a1000
![image](https://user-images.githubusercontent.com/17108995/65910265-a739e900-e3ca-11e9-8292-02f62a9bc3d8.jpg)

**Comment by mithrendal** [comment]
Ddfskip2 a1000
![image](https://user-images.githubusercontent.com/17108995/65910415-ea945780-e3ca-11e9-957d-3ea245ebd4b1.jpg)

**Comment by mithrendal** [comment]
Ddf7 a1000
![image](https://user-images.githubusercontent.com/17108995/65910517-292a1200-e3cb-11e9-8402-f640131a09a3.jpg)

**Comment by dirkwhoffmann** [comment]
Thanks a lot 😃👍. I'll upload the images to the repo asap.

**Comment by mithrendal** [comment]
I have found a quicker way of transferring the disks. I only have to transfer the first three tracks or so. Dont have to wait the full 5 Minutes.  I cancel the transfer after 20 seconds or so. This seems to be enough as your testprg is very small and it is written to track 0 upwards... 🤓

So it was possible to finish the non hires test today. Tomorrow I like to finish the hires tests.

**Comment by dirkwhoffmann** [comment]
A1000 reference images have been uploaded 😎.

**Comment by mithrendal** [comment]
![B36103F6-E135-4202-B63C-E1CB663520E6](https://user-images.githubusercontent.com/17108995/65995414-c3ef2300-e495-11e9-9f65-e1337dad7c19.jpeg)
ddfstrt2h a1000

**Comment by mithrendal** [comment]
![340D07B4-DE6B-400F-A746-A5240CC6CFEF](https://user-images.githubusercontent.com/17108995/65995942-c140fd80-e496-11e9-88a9-8d264856c5ee.jpeg)
ddfstrt3h a1000

**Comment by mithrendal** [comment]
![08B8FD90-55B6-4B9F-A070-62D27080332C](https://user-images.githubusercontent.com/17108995/65996078-0402d580-e497-11e9-9776-0ddcab597622.jpeg)
ddfstrt4h a1000

**Comment by mithrendal** [comment]
![EFF95BDB-D6DE-46A0-81E0-141499F7580E](https://user-images.githubusercontent.com/17108995/65996204-45938080-e497-11e9-8cb9-5f1f5fefa283.jpeg)
ddfstrt5h a1000

**Comment by mithrendal** [comment]
![E3CD65D5-1A60-4630-8EE4-686295E6BF8E](https://user-images.githubusercontent.com/17108995/65996475-c05c9b80-e497-11e9-8a2c-46abf11ba642.jpeg)
ddfstrt6h a1000

**Comment by mithrendal** [comment]
![A4F95D2E-C411-4487-B851-92186CB16F5C](https://user-images.githubusercontent.com/17108995/65996728-4678e200-e498-11e9-869a-f02888ca0ac2.jpeg)

ddfstrt7h a1000

**Comment by mithrendal** [comment]
![FF68F2F5-EC59-4FDA-9BC5-73CD029A04CB](https://user-images.githubusercontent.com/17108995/65996832-7aec9e00-e498-11e9-8299-cb8156f130bf.jpeg)

ddfstrt8h a1000

**Comment by mithrendal** [comment]
![9320D7E5-3425-4587-99B3-4F0F191EE7B1](https://user-images.githubusercontent.com/17108995/65996935-b4bda480-e498-11e9-8fc5-66d75277bfd1.jpeg)
ddfstrt9h a1000

**Comment by dirkwhoffmann** [comment]
Many thanks 👍!!! I've uploaded the images to the repo. 

I think we have a pretty nice test suite now, with reference images from three different Agnus versions. 

If I interpret the images correctly, the A1000 Agnus differs as follows:

- Very small and very large values in DDFSTRT and DDFSTOP don't trigger. In case of the A500, all values trigger except those that exceed the number of horizontal DMA cycles (the horizontal counter wraps over before reaching those values). 
- When DDSTRT or DDFSTOP triggers, the A1000 toggles the DDF flipflop whereas the A500 sets or clears it.

Implementing the toggle functionality might be tricky. First I need to figure out how DMA works if DDFSTOP is not reached (which means that DMA is not stopped at the end of the rasterline).
